export default {
  login: 'login',
  register: 'register',
  logout: 'logout',
  applyActivity: 'applyActivity',
  getPersonalActivity: 'getPersonalActivity',
  deleteActivity: 'deleteActivity',
  getNewActivity: 'getNewActivity',
  passActivity: 'passActivity',
  returnActivity: 'returnActivity',
  getActivity: 'getActivity',
  joinActivity: 'joinActivity',
  unJoinActivity: 'unJoinActivity',
  getJoinedActivity: 'getJoinedActivity',
  getUserInfo: 'getUserInfo',
  updateInfo: 'updateInfo',
  getAllUser: 'getAllUser',
  setAdmin: 'setAdmin',
  setNormal: 'setNormal',
  deleteUser: 'deleteUser',
  addNotice: 'addNotice',
  getNotice: 'getNotice'
}